spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-muddy-mud-ah5se4u6-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WkqMlXVsjc28
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.jpa.properties.hibernate.jdbc.batch_size=4000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=true


#crate a account on cloudinary and get below keys
cloudinary.cloud-name=djb9em35j
cloudinary.api-key=787238678776677
cloudinary.api-secret=idCB93cGaK5r8OTK-QNWIcdMMDY

#cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
#cloudinary.api-key=${CLOUDINARY_API_KEY}
#cloudinary.api-secret=${CLOUDINARY_API_SECRET}

